#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#This notebook will mainly be used for the Car Severity Analysis Tool Project. 


# In[2]:


import pandas as pd
import numpy as np


# In[4]:


print("Hello Capstone Project Course!")

